### ISSUE TITLE
"minibar" einstellbar machen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/minibar#2]
soll die minibar überhaupt angezeigt werden..

im profil? oder systemweit?

**Comment by staabm** [comment]
wir hatten ein flag am user

![grafik](https://user-images.githubusercontent.com/120441/54344592-80d87a00-4641-11e9-9b3c-1514cb534d40.png)

**Comment by tbaddade** [comment]
Sehe ich wenn eher Systemweit. Das Der Admin entscheidet. Denn er kann Elemente speziell für das Projekt entwicklen.

Da die Elemente selbst entscheiden können ob diese im Popup erscheinen oder nicht, wäre es eventuell auch hinfällig. https://github.com/FriendsOfREDAXO/minibar/commit/6434a8c436051e7d14c000823d411f43fcedcf61

**Comment by staabm** [comment]
siehe https://github.com/redaxo/redaxo/commit/34cc319ecd28d24f509f067fc3d3e2830b63d4ea

![grafik](https://user-images.githubusercontent.com/120441/54344756-ddd43000-4641-11e9-8d4e-4d8bdf933978.png)

**Comment by staabm** [comment]
![grafik](https://user-images.githubusercontent.com/120441/54344849-18d66380-4642-11e9-9ffd-90fa9811f7ae.png)

**Comment by staabm** [comment]
ich hab das issue hier umbenannt auf "minibar einstellbar machen" um die allgemeine frage zu aktiv/inaktiv zu klären.

ob sie nur in popups dann noch aktiv sein soll wird in issue #7 behandelt.

ich hatte das hier urspr. vermischt/verwechselt

**Comment by tbaddade** [comment]
Das Feld wird bereits angelegt  (https://github.com/FriendsOfREDAXO/minibar/issues/2#issuecomment-472766179) siehe https://github.com/FriendsOfREDAXO/minibar/commit/65e88913244ee98ddf22d17ab291843d3d59e291

Offen wäre, dass Der User dann das Feld in der Profilseite beeinflussen kann.
