### ISSUE TITLE
Aussehen/Design

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/minibar#20]
https://github.com/redaxo/redaxo/issues/2310

**Comment by tbaddade** [comment]
Mag jemand das Design umsetzen?

**Comment by eaCe** [comment]
Wäre das so in Ordnung?

![minibar](https://user-images.githubusercontent.com/2708231/57606666-a0b8eb00-7569-11e9-9a71-6787ea38712f.jpg)

Nur über `be_style/vendor/font-awesome` sind die Icons offline/online nicht verfügbar (betrifft das Frontend)

**Comment by eaCe** [comment]
Wenn jemand möchte kann hier getestet werden:
https://github.com/eaCe/minibar

Kann gerne einen PR erstellen

**Comment by staabm** [comment]
@skerbis ich vermute du bist einer der intensivsten nutzer der minibar.
passt das vorgschlagene Theme für dich? müsstest du deine eigenen elemente anpassen aufgrund des neuen styles?

**Comment by skerbis** [comment]
> müsstest du deine eigenen elemente anpassen aufgrund des neuen styles?

Ich denke nicht. Die Gestaltung passt für mich

**Comment by skerbis** [comment]
@eaCe PR wäre toll

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/minibar/pull/57 
@eaCe danke. Release folgt in Kürze
