### ISSUE TITLE
Compile scss beim installieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/minibar#24]
Wenn be-style vorhanden.. dann von dort den compiler verwenden.

Aber ohne diese EP gymnastik wie es die be-style addons machen

**Comment by tbaddade** [comment]
Finde ich nicht gut … ich würde gern den compiler mit der nächsten Major-Version komplett entfernen wollen

**Comment by staabm** [comment]
Warum möchtest du ihn entfernen?

Ich finde den php compiler schön da ich auf keinem meiner rechner ein scss installiert hab

**Comment by staabm** [comment]
Ich glaube auch das einige user den compile-schalter aus der package.yml. verwenden und nicht in der Lage sind scss zu installieren
