### ISSUE TITLE
Installer Element

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/minibar#30]
Hinweis ausgeben, wenn zu installierten Packages updates verfügbar sind

**Comment by staabm** [comment]
Vllt auch allgemeiner via Notification Element, statt eigenem 
https://github.com/FriendsOfREDAXO/minibar/issues/31

**Comment by skerbis** [comment]
Ja 👍Hinweis evtl. aber nur bitte bei „kritischen“ Updates.
