### ISSUE TITLE
Frontend Artikel bei Hover —> Falscher Link …lazyload

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minibar#35]
Beim Hover über den Artikel-Button wird zum Artikel mit der ID 1  (Fehlerartikel) geleitet. 
Die Ansicht ändert sich dann
vor dem Hover
![Bildschirmfoto 2019-03-17 um 16 19 01](https://user-images.githubusercontent.com/791247/54493445-7849a300-48d0-11e9-8f66-ad579b74804a.png)
Beim Hover
![Bildschirmfoto 2019-03-17 um 16 20 21](https://user-images.githubusercontent.com/791247/54493451-87305580-48d0-11e9-9e56-af54b4bb36e6.png)

Problem tritt nur im Frontend auf

Eingesetzter Rewriter: yrewrite

**Comment by skerbis** [comment]
Update: Ohne Rewriter tritt das Problem nicht auf

**Comment by TobiasKrais** [comment]
Kann den Bug bestätigen. Bei mir geht er allerdings nicht zu Artikel 1 sondern zum Fehlerartikel.

**Comment by anveno** [comment]
> Kann den Bug bestätigen. Bei mir geht er allerdings nicht zu Artikel 1 sondern zum Fehlerartikel.

Dito. Sobald renderComplete() ausgeführt wird, ist rex_article::getCurrent() falsch und ich erhalte den Fehlerartikel. yrewrite habe ich ebenfalls aktiv.

**Comment by staabm** [comment]
Vermutlich müsste das element hier mit yrewrite::init() und yrewrite::getArticleIdByUrl() arbeiten, wenn das addon installiert ist

**Comment by staabm** [comment]
@skerbis kannst du testen ob 
`load: late` in der package.yml der minibar (analog project addon) helfen würde gegen das gemeldete problem?

**Comment by skerbis** [comment]
leider keine Änderung

**Comment by Geri2017** [comment]
Hat sich eigentlich mit dem frontend hover-bug schon etwas getan?

**Comment by staabm** [comment]
Der Fehler ist bekannt und bisher hat niemand Zeit investiert was dagegen zu tun.

Ich für meinen Teil habe nicht geplant demnächst daran zu arbeiten. Patches für das Problem sind willkommen

**Comment by TobiasKrais** [comment]
`load: late` in der package.yml funktioniert nicht. Das hatte ich schon probiert.
Auch habe ich probiert es so zu lösen wir ein Problem im cookie_consent Addon gelöst haben: https://github.com/FriendsOfREDAXO/cookie_consent/blob/9e6550793389fda364a271d736ea74bcae7d227b/boot.php#L13. Aber auch das hat nicht geholfen.
Ich konnte den Fehler nicht eingrenzen, so gerne ich hier mitarbeiten würde. Die Frage, die sich mir stellt, ob man hier überhaupt lazyload verwenden muss.

**Comment by skerbis** [comment]
Ich denke bei den paar Infos braucht man das Lazyload im Frontend nicht, das wäre dann ein möglicher Fix.

**Comment by staabm** [comment]
PR welcome.

**Comment by skerbis** [comment]
Ich kümmere mich drum

**Comment by skerbis** [comment]
ich geb's auf. Das will nicht funktionieren bei mir. Sobald ich yRewrite im Einsatz habe bekomme ich nicht die korrekte Backend-Adresse.

**Comment by staabm** [comment]
@skerbis lass uns das zusammen in Landshut anschauen

**Comment by eaCe** [comment]
Wäre es denkbar dem ```rex_minibar_element``` die Artikel-Id als Parameter mit zu übergeben? 

https://github.com/FriendsOfREDAXO/minibar/blob/55988a942c3abb9bbe7c14c53e18bd0f9a5485d1/fragments/core/minibar/minibar_element.php#L18

zu:

```php
$url = $context->getUrl(['lazy_element' => $elementId, 'article_id' => rex_article::getCurrentId()] + rex_api_minibar::getUrlParams());
```

Und dann in der renderComplete Funktion:

https://github.com/FriendsOfREDAXO/minibar/blob/55988a942c3abb9bbe7c14c53e18bd0f9a5485d1/lib/element/article.php#L43

```php
$articleId = rex_get('article_id');
$article = rex_article::get($articleId);
```

**Comment by staabm** [comment]
danke für die idee.

@skerbis würde der vorschlag das gemeldete Problem lösen? kannst du das testen?

**Comment by anveno** [comment]
Moin. Die Idee von @eaCe funktioniert bei mir.

**Comment by skerbis** [comment]
kann ich bestätigen , müsste noch um current language ergänzt werden

**Comment by TobiasKrais** [comment]
Vielen Dank euch allen und auch für die neue Version. Es funktioniert 1a!

**Comment by skerbis** [comment]
Danke an @eaCe für den Tipp
