### ISSUE TITLE
Artikel-Element::Metadatenanzeige einschränken

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minibar#39]
Bei vielen Metadaten (vor allem nicht befüllte) könnte der Artikelbutton unübersichtlich werden. 
Vorschlag: Metadaten mit leeren Values nicht auflisten.

**Comment by eaCe** [comment]
Man könnte das über ein weiteres Einstellungs-Dropdown auf der System-Seite abbilden:

![minibar](https://user-images.githubusercontent.com/2708231/57611368-fe056a00-7572-11e9-927a-0bb54e140603.png)

Und dann in der Extension anpassen. Wenn das so gewünscht/in Ordnung ist, kann ich einen PR erstellen.

**Comment by staabm** [comment]
kann man wegen mir so machen, wenn es hilft.

da wir ja hier im addon unterwegs sind kann man bissl ausprobieren.

**Comment by skerbis** [comment]
@eaCe gerne 👍

**Comment by staabm** [comment]
closed by https://github.com/FriendsOfREDAXO/minibar/pull/49
