### ISSUE TITLE
Externe minibar Elemente: css und js

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minibar#42]
Wie sollen externe Elemente eigene css und js liefern? Sinnvoll wäre hier eine Function oder Methode.

**Comment by staabm** [comment]
Ich selbst hab noch keine gebaut.. aktuell stelle ich mir es so vor:
Die elemente sind teil eines addons und dieses kann css/js liefern, wie es addons schon immer tun.
Ich sehe aktuell keinen bedarf dass elemente selbst js/css liefern sollten.

Ggf. Kann man das gemeinsam durchdenken wenn man ein konkretes Beispiel hat

**Comment by skerbis** [comment]
Ich möchte die „last changed history“ der Quicknavi im Frontend einsetzen. Dafür benötige ich CSS-Stile für die Listen-Darstellung im drop-up. Diese kann man natürlich über einen outputfilter oder inline im drop-up verknüpfen. Da die minibar schon den Weg über den outputfilter geht, könnte man dies evtl. allgemein als function zur Verfügung stellen, so dass es einen einheitlichen Weg gäbe.

**Comment by tbaddade** [comment]
Die Minibar sollte das liefern und nicht die Elemente. Wenn etwas fehlt müssten wir das ergänzen.

**Comment by staabm** [comment]
> Die Minibar sollte das liefern und nicht die Elemente.

Ich bin mir unsicher ob es gut wäre einen „minibar-addon spezifischen“ weg/api zu erzeugen um css/js ins frontend zu bringen.
Es gibt ja mittlerweile einige addons die css/js ins frontend einschleusen und dies passiert dort meist über den gleichen weg (output-filter).

Ggf. Sollten wir im core was vergleichbares wie rex-view::addCss/js haben - aber fürs frontend.
Addon spezifische wege für dieses todo würde ich nur einbauen wenn es wirklich notwendig wird, d.h. Das unterschiedliche addons das auch unterschiedlich tun müssen

**Comment by skerbis** [comment]
Ok

**Comment by staabm** [comment]
Ich wollte die diskussion nicht abwürgen. Wer andere Meinungen und Argumente hat, darf die gerne anbringen

**Comment by skerbis** [comment]
Ich denke nicht, dass die minibar alle möglichen Stile zur Darstellung selbst mitliefern muss. Das würde sie unnötig aufblähen. @tbaddade. Den Verweis zum Core fand ich gut. @staabm Für meinen Zweck kann ich die Stile inline liefern. Bei komplexeren Widgets kann man ja auf den Outputfilter zurückgreifen.

**Comment by tbaddade** [comment]
> Für meinen Zweck kann ich die Stile inline liefern. 

Das sollte eben nicht passieren. Die Minibar sollte das Verhalten und Aussehen vorgeben und nicht jedes einzelne Element für sich. Das würde m.E. nur ein reinstes Chaos werden.

**Comment by skerbis** [comment]
Hier mal ein Screenshot von dem was ich vorhabe. (Ist noch in Arbeit, noch nicht final) - Gedacht für's Frontend. 

![Bildschirmfoto 2019-03-25 um 11 47 31](https://user-images.githubusercontent.com/791247/54916013-c70ec280-4ef8-11e9-87d3-3be1ea46604e.png)

**Comment by skerbis** [comment]
Ich werde die nötigen Stile nun erstmal in dem Button inline mitliefern, bis wir einen allgemein gültigen Weg gefunden haben.

**Comment by staabm** [comment]
Ok.. schauen wir uns dann an wie es am ende aussieht
