### ISSUE TITLE
Systemlog zeigt gelbe Fahne obwohl Log leer

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minibar#53]
<img width="1130" alt="Bildschirmfoto 2019-07-03 um 10 57 58" src="https://user-images.githubusercontent.com/791247/60578443-7e7d6580-9d81-11e9-9384-bca14ba65b9e.png">

**Comment by staabm** [comment]
hier ist die logik beschrieben die diese farben ermittelt:

https://github.com/FriendsOfREDAXO/minibar/blob/78a6846cbbe65bd1a8070303966b395b1efbc739/lib/element/syslog.php#L17-L25

ich vermute in deinem fall hast du eine installation die neu ist und noch keine 24h existiert?

**Comment by skerbis** [comment]
Ah ok ..  dann warte ich mal ab

**Comment by staabm** [comment]
hab ich richtig geraten und deine installion ist neu?

**Comment by skerbis** [comment]
ja die minibar ist frisch installiert.

**Comment by staabm** [comment]
nicht die minibar... die redaxo installation?

**Comment by skerbis** [comment]
ne, die REDAXO-Installation ist von 2017 und immer wieder aktualisiert

**Comment by staabm** [comment]
hm ok, dann kannste vllt mal durch die 5 oben genannten zeilen durchdebuggn und schauen warum es gelb wird

**Comment by skerbis** [comment]
ich werde mich drum kümmern ..

**Comment by skerbis** [comment]
Kann ich aktuell nicht mehr reproduzieren. Ich close hier erstmal.

**Comment by christophboecker** [comment]
Ich hab einen Verdacht: eine Suche im kompletten Source-Verzeichnis (Addons und Core) gab nur eine einzige Fundstelle für den String `'rex_syslog_last_seen'`. Wenn an keiner Stelle irgendwo dieser Session-Wert gesetzt wird, läuft auch jede Abfrage dagegen ins Leere. 

Als Gegenprobe habe ich die `redaxo/src/core/pages/system.log.redaxo.php` am Ende um eine Zeile ergänzt:
```php
...
echo $message;
echo $content;

rex_set_session('rex_syslog_last_seen', filemtime($logFile) );
```
Und siehe da:
<img width="350" alt="grafik" src="https://user-images.githubusercontent.com/10065904/89711904-83054c00-d98d-11ea-9845-bdd86e30ac04.png">

Über die Minibar gelöst durch einen Zusatz in der `boot.php`:
```php
if (rex::isBackend()) {
    ...
    if (rex_be_controller::getCurrentPage() == 'system/log/redaxo') {
        rex_extension::register('OUTPUT_FILTER', function (rex_extension_point $ep) {
            rex_set_session('rex_syslog_last_seen', filemtime(rex_logger::getPath()) );
        });
    }
```
Der zusätzliche Output-Filter bewirkt, dass beim Anzeiger der Log-Seite die Flagge erst noch mal gelb ist. Läst man den Outputfilter weg, ist beim Anzeiges der Log-Seite die Flagge sofort grün.

**Comment by christophboecker** [comment]
Nächstes Problem: Die Minibar wird wohl generiert, bevor die Seite aufgebaut wird. Wurde zuvor die Logdatei angesehen, ist die Flagge grün gesetzt. Passiert danach beim weiteren Seitenaufbau der Fehler und ein Logeintrag wird geschrieben, kommt die gelbe Flagge erst beim nächsten Seitenaufruf. Das ist m.E. zu spät. Hab dafür aber noch keine Idee.

**Comment by staabm** [comment]
> Nächstes Problem: Die Minibar wird wohl generiert, bevor die Seite aufgebaut wird. Wurde zuvor die Logdatei angesehen, ist die Flagge grün gesetzt. Passiert danach beim weiteren Seitenaufbau der Fehler und ein Logeintrag wird geschrieben, kommt die gelbe Flagge erst beim nächsten Seitenaufruf. Das ist m.E. zu spät. Hab dafür aber noch keine Idee.

Bitte als separates issue

**Comment by christophboecker** [comment]
Der obige Code für die Lösung gehört natürlich in die Syslog-Klasse :-)
