### ISSUE TITLE
prüfen ob wir weniger fragmente überschreiben können

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/minibar#6]
damit wir weniger stark von der redaxo version abhängig sind (andernfalls muss man immer änderungen in fragmenten aus dem core nacharbeiten)

**Comment by tbaddade** [comment]
Nur das `bottom.php` Fragment wäre jetzt noch Coreabhängig. Der Minibar Ordner könnte eine Ebene höher geschoben werden.

**Comment by staabm** [comment]
ok ich denke damit kann man erstmal leben. danke
