### ISSUE TITLE
Backend: Minibar verhindert öffnen des mobilen Menüs

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minibar#65]
Ist die Minibar aktiviert lässt sich das mobile Menü in REDAXO nicht mehr öffnen.

**Comment by staabm** [comment]
Was ist „das mobile menu“?

**Comment by skerbis** [comment]
<img width="500" alt="Bildschirmfoto 2020-01-25 um 12 09 20" src="https://user-images.githubusercontent.com/791247/73120217-b3464980-3f6b-11ea-8ec8-8f639e2cd54b.png">

**Comment by staabm** [comment]
Fix welcome

**Comment by skerbis** [comment]
Ich bin noch nicht dahinter gekommen. Bzw. da das REDAXO Backend mobil untauglich ist aus meiner Sicht, habe ich es nicht weiter verfolgt.

**Comment by tbaddade** [comment]
> Bzw. da das REDAXO Backend mobil untauglich ist aus meiner Sicht

PR welcome

**Comment by skerbis** [comment]
@tbaddade klar. Aber erst für 6.x falls wir das Framework ersetzen
