### ISSUE TITLE
minibar erzeugt Fehler in Redaxo console

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/minibar#82]
**Description / Beschreibung**
bei aktiviertem Addon können console Kommandos nicht ausgeführt werden

**Affected versions / Verwendete Versionen**
2.3.1

REDAXO: 5.13.3
PHP: 8.0
Database: 
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**
Exception trace:
  at /my/path/to/redaxo/src/core/lib/rex.php:348
 rex::getRequest() at /my/path/to/redaxo/src/core/lib/request.php:255
 rex_request::isPJAXRequest() at /my/path/to/redaxo/src/addons/minibar/boot.php:61
 require() at /my/path/to/redaxo/src/core/lib/packages/package.php:280
 rex_package->includeFile() at /my/path/to/redaxo/src/core/lib/packages/package.php:427
 rex_package->boot() at /my/path/to/redaxo/src/core/lib/console/application.php:93
 rex_console_application->loadPackages() at /my/path/to/redaxo/src/core/lib/console/application.php:48
 rex_console_application->doRunCommand() at /my/path/to/redaxo/src/core/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /my/path/to/redaxo/src/core/lib/console/application.php:23
 rex_console_application->doRun() at /my/path/to/redaxo/src/core/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /my/path/to/redaxo/src/core/console.php:39
 require() at /my/path/to/redaxo/bin/console:11

**Comment by skerbis** [comment]
Sollte im aktuellen Core behoben sein: 
https://github.com/redaxo/redaxo/pull/5159
Bitte REDAXO updaten.
