### ISSUE TITLE
Installation unter 5.16 schlägt fehl

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minibar#86]
`../../be_style/vendor/font-awesome/scss/font-awesome` file not found for @import: line: 7, column: 1

Icons müssen neu generiert werden

**Comment by my-steffen** [comment]
Ah es gibt schon ein Ticket ;)

**Comment by skerbis** [comment]
sollte eigentlich mit 2.4.0 behoben sein @my-steffen

**Comment by my-steffen** [comment]
`../../be_style/vendor/font-awesome/scss/font-awesome` file not found for @import: line: 7, column: 1
auf > 2.4.1 Aber mein Aktuelle Version klappt ja (2.3.1) ;) @skerbis

**Comment by my-steffen** [comment]
kein Stress

**Comment by skerbis** [comment]
jetzt aber 
https://github.com/FriendsOfREDAXO/minibar/releases/tag/2.4.1

**Comment by skerbis** [comment]
@my-steffen ok. Das Problem tritt nur beim Update auf und sollte mit 2.4.2 behoben sein.
